//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipUygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class satis_detaylari
    {
        public int satis_detay_id { get; set; }
        public Nullable<int> satis_id { get; set; }
        public Nullable<int> urun_kodu { get; set; }
        public int miktar { get; set; }
        public decimal fiyat { get; set; }
    
        public virtual satislar satislar { get; set; }
        public virtual urunler urunler { get; set; }
    }
}
