//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipUygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class satislar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public satislar()
        {
            this.satis_detaylari = new HashSet<satis_detaylari>();
        }
    
        public int satis_id { get; set; }
        public Nullable<int> musteri_id { get; set; }
        public Nullable<int> personel_id { get; set; }
        public Nullable<System.DateTime> satis_tarih { get; set; }
        public string notlar { get; set; }
    
        public virtual musteriler musteriler { get; set; }
        public virtual personeller personeller { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis_detaylari> satis_detaylari { get; set; }
    }
}
