//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipUygulamasi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class stok_takip_dbEntities : DbContext
    {
        public stok_takip_dbEntities()
            : base("name=stok_takip_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kategoriler> kategoriler { get; set; }
        public virtual DbSet<musteriler> musteriler { get; set; }
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<satis_detaylari> satis_detaylari { get; set; }
        public virtual DbSet<satislar> satislar { get; set; }
        public virtual DbSet<tedarikciler> tedarikciler { get; set; }
        public virtual DbSet<urunler> urunler { get; set; }
        public virtual DbSet<yetkiler> yetkiler { get; set; }
    }
}
