//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StokTakipUygulamasi
{
    using System;
    using System.Collections.Generic;
    
    public partial class urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public urunler()
        {
            this.satis_detaylari = new HashSet<satis_detaylari>();
        }
    
        public int urun_kodu { get; set; }
        public string urun_adi { get; set; }
        public Nullable<int> kategori_id { get; set; }
        public Nullable<int> tedarikci_id { get; set; }
        public Nullable<int> stok_adedi { get; set; }
        public Nullable<decimal> fiyat { get; set; }
        public string aciklama { get; set; }
    
        public virtual kategoriler kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<satis_detaylari> satis_detaylari { get; set; }
        public virtual tedarikciler tedarikciler { get; set; }
    }
}
